Update batch.py to support both cnvrg cli and cnvrgv2
AccessibleAI/ailibrary pull request #79
Opened 2024-02-26 14:59 UTC by DannyAtal

2024-02-26 15:52 UTC, OfirCnvrg requested changes

2024-02-26 15:52 UTC, OfirCnvrg commented on py_batch_predict/batch.py
> +        print('Uploading {output_file} to dataset {dataset}'.format(output_file=output_file, dataset=dataset))
Since it's the same message, declare it once outside of the if block, and use it in both prints

2024-02-26 15:52 UTC, OfirCnvrg commented on py_batch_predict/batch.py
> +    if os.system('cnvrgv2 > /dev/null 2>&1')== 0:
prettify:
...) == 0:

you sure this works? when I try this with gibberish I still get > 0:

<img width="408" alt="image" src="https://github.com/AccessibleAI/ailibrary/assets/71211765/12d42be3-9858-4226-afdb-5f83ff3245ee">

2024-02-26 15:52 UTC, OfirCnvrg commented on py_batch_predict/batch.py
> +    elif os.system('cnvrg > /dev/null 2>&1')==0:
prettify:
...) == 0:

2024-02-26 18:01 UTC, DannyAtal commented on py_batch_predict/batch.py
> +    if os.system('cnvrgv2 > /dev/null 2>&1')== 0:
done

2024-02-26 18:01 UTC, DannyAtal commented on py_batch_predict/batch.py
> +    elif os.system('cnvrg > /dev/null 2>&1')==0:
done

2024-02-26 18:01 UTC, DannyAtal commented on py_batch_predict/batch.py
> +        print('Uploading {output_file} to dataset {dataset}'.format(output_file=output_file, dataset=dataset))
done

2024-02-28 12:19 UTC, OfirCnvrg approved these changes

2024-02-28 12:19 UTC, merged